### ISSUE TITLE
Some relative links are incorrectly treated as external

### ISSUE THREAD

**Issue by adueppen** [aloskutov/eleventy-plugin-external-links#19]
Links that start with a slash are correctly treated as relative, but ones that don't are interpreted as having a hostname of the first part of the link and therefore are seen as external links by the plugin.

e.g.
`/projects/` -> `<a href="/projects/">projects</a>`
`projects/` -> `<a href="projects/" rel="noopener external" target="_blank">projects</a>`

**Comment by aloskutov** [comment]
This is because it is not possible to unambiguously determine whether it is a path or a domain name by parsing the URL string.

There are two options for solving the problem:
1. Use a forward slash ("/", "./", or "../") to specify the path and domain name without the double slash.
2. Using a double slash to denote a domain name ("//www.exapmle.com").

The first option is used by browsers (domains without explicit protocol and double slashes) - currently used. The second option is closer to RFC 1738 and might be worth switching to.
